### ISSUE TITLE
Upgrade AAVE to 3.0.0 Schema

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#1519]
Issues to address when we do this: 

### Tasks
- [x] Upgrade aave forks to latest lending schema/SDK
- [x] Add liquidation Rev to Aave forks: https://github.com/messari/subgraphs/issues/1831
- [x] Ensure all helper fields are prepended with `_` before deployment: https://github.com/messari/subgraphs/issues/1084
- [x] Ensure no immutable entity IDs are changed (protocol.id, market.id) (note: this is case sensitive)
- [x] Simplify Aave V3 (and forks) (see spark lend manifest for what to do)
- [x] add flashloan data
- [x] Ensure positions are properly labeled with isolation type in aave v3: https://github.com/messari/subgraphs/issues/1491
- [x] Will need to include this during upgrade: https://github.com/messari/subgraphs/pull/1669 
    - [need clarification](https://github.com/messari/subgraphs/pull/1669#issuecomment-1510016903)
- [ ] ~~(optional) treasury data: https://github.com/messari/subgraphs/issues/163~~
     - [need more specifics](https://github.com/messari/subgraphs/issues/163#issuecomment-1510002233)
     - [decided to not do this atm](https://discord.com/channels/@me/1091205155921338448/1097901589102080071)

**Comment by dmelotik** [comment]
Will also allow us to get aave flashloan data

**Comment by dmelotik** [comment]
Another note: aave v3 and forks can be refactored to be simpler (see spark lend). We might as well do that change in this PR as well

**Comment by ishraq8** [comment]
@dmelotik just to confirm, this will not effect endpoints for protocol metrics right?

**Comment by dmelotik** [comment]
Good point @ishraq8. We need to discuss how we can go about this from a consumption standpoint. 

To answer the question, this affects endpoints. The upgrade creates breaking changes on the endpoint. But, our service already supports the schema we will be moving to in this issue.

The question is, what work needs to be done in order to support this update, if any?

**Comment by tnkrxyz** [comment]
I am almost done with the refactoring. @dmelotik , @bye43 , one quesiton for you is whether the upgraded subgraphs need to be QAed? Since the upgrade/refactoring adds new logics and changes existing logic (transfers), I feel more comfortable if any protocol specialist can help take a look.

**Comment by ishraq8** [comment]
@tnkrxyz happy to take a look for QA, I think it is best practice to QA these refactoring. Give me a heads up when they are ready.

**Comment by dmelotik** [comment]
@ishraq8 the only thing that should change is the aave v3 positions since we are now splitting them on the borrow side between stable and variable borrows.

And all of the new fields/entities from the new schema, so we should make sure they make sense, but the tvl, revenue, usage, on the protocol/pools should be exactly the same

**Comment by tnkrxyz** [comment]
> @tnkrxyz happy to take a look for QA, I think it is best practice to QA these refactoring. Give me a heads up when they are ready.

@ishraq8  I made some final changes and re-deployed the subgraphs. Unfortunately, some of subgraphs will take a long time to sync (aave-v2/v3-polygon etc). I will let you know once it is fully synced.

**Comment by ishraq8** [comment]
> @ishraq8 the only thing that should change is the aave v3 positions since we are now splitting them on the borrow side between stable and variable borrows.
> 
> And all of the new fields/entities from the new schema, so we should make sure they make sense, but the tvl, revenue, usage, on the protocol/pools should be exactly the same

Good to note, i figured it could be a quick look for a set of eyes.

**Comment by ishraq8** [comment]
@tnkrxyz @dmelotik went through the positional data on the v3.0.1 schemas and they are accurate compared to what is on the explorer. Positional data is accurate and depends on code review.

**Comment by tnkrxyz** [comment]
> @tnkrxyz @dmelotik went through the positional data on the v3.0.1 schemas and they are accurate compared to what is on the explorer. Positional data is accurate and depends on code review.

@ishraq8 , great, thx! There are a few subgraphs that are still syncing (e.g. [aave-v2-polygon](https://thegraph.com/hosted-service/subgraph/tnkrxyz/aave-v2-polygon), [aave-v3-optimism](https://thegraph.com/hosted-service/subgraph/tnkrxyz/aave-v3-optimism)) and will take a long time before they are fully synced. I also fixed a deployment error for aave-v2-ethereum and radiant-arbitrum. See https://github.com/messari/subgraphs/pull/1993#issue-1660224405 for a complete list of subgraphs.

**Comment by dmelotik** [comment]
@ishraq8 can you also take a look at revenue detail in markets. The new field should separate flashloan and liquidation revenue out

**Comment by dmelotik** [comment]
tnkrxyz is still working on an issue from the revenue on aave v3 eth

**Comment by ishraq8** [comment]
will do,  thanks for heads up :)
