### ISSUE TITLE
Subgraph dashboard Issues: Deployment overlay for derivatives and DefiLlama overlay for Curve

### ISSUE THREAD

**Issue by bye43** [messari/subgraphs#2124]
```[tasklist]
### Tasks
- [ ] Add deployment overlay for derivatives on validations dashboard
- [ ] Fix defiLlama TVL overlay for Curve on validation dashboard
- [ ] GH issue <> subgraph status sync broken
```
@dhruv-chauhan Looks like the overlay search bar that exists for other protocol types is not populating/present for derivatives perps/options:
![Screen Shot 2023-05-15 at 5 35 57 PM](https://github.com/messari/subgraphs/assets/107651107/88907b02-c92e-47a1-b506-8f4efc05c8fd)
In addition, when trying to overlay DefiLlama Curve data on the Curve subgraphs it looks like the API call is timing out. This might be cause defiLlama changed their endpoint or slug

**Comment by bye43** [comment]
Also @dhruv-chauhan looks like in 2.2.15 the dashboard is no longer syncing with GH issues, so the `prod` subgraphs w/ github issues are not turning orange
