### ISSUE TITLE
Build friend.tech subgraph

### ISSUE THREAD

**Issue by melotik** [messari/subgraphs#2372]
https://www.friend.tech/

```[tasklist]
### Tasks
- [x] Create schema/define important metrics
- [x] Build Base subgraph
```

**Comment by bye43** [comment]
@dhruv-chauhan Going through some metrics still, but a few QA comments (these may or not be issues, but figured I would let you know)

- [ ] The TVL is about 17% different than defiLlama and it looks like this starts around 09/13
![Image](https://github.com/messari/subgraphs/assets/107651107/874b8664-82b1-4e85-84bd-49b7ab58ab8f)

- [ ] The daily active buyers (which also means users) seem to be less than what [Dune](https://dune.com/msilb7/friendtech-on-base-activity) and Token Terminal are reporting 35K on the largest spike and we are reporting around 21K
![Image](https://github.com/messari/subgraphs/assets/107651107/5a6f8bcf-caf3-475b-98bc-f8436c0055c5)
![Image](https://github.com/messari/subgraphs/assets/107651107/f3ec8bfa-da2c-4c5f-a043-b3b86f33bf5a)

- [ ] The buy and sell volumes seem to be different than this [Dune](https://dune.com/cryptokoryo/friendtech) too
![Image](https://github.com/messari/subgraphs/assets/107651107/9712925c-f0b9-436f-be4a-e31d8132cb86)
![Image](https://github.com/messari/subgraphs/assets/107651107/76ebfc27-fac1-46b1-8681-b0698933d279)

**Comment by bye43** [comment]
@dhruv-chauhan the buy and sell volume still looks off on the newer version. And did we remove the traders and subjects entities? If so, was there a reason?

**Comment by dhruv-chauhan** [comment]
`Failed to deploy to Graph node https://api.thegraph.com/deploy/: subgraph failure::[Base Mainnet] chain is no longer supported on the hosted service. Please deploy to the decentralized network.`

@melotik @bye43
